import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { testCalculate } from '../services/puzzleCalculator'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [boardOutput, setBoardOutput] = useState<string>("Click calculate to test.");

  const calculate = () => {
    const boardString = testCalculate();
    setBoardOutput(boardString);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Ni no Kuni: Cross Worlds Puzzle Solver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Puzzle Sover
        </h1>

        <div style={{margin: 15, display: 'flex', flexDirection: 'column'}}>
          <button onClick={calculate}>Calculate</button>

          <textarea cols={200} rows={15} value={boardOutput}></textarea>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
