import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { PuzzleBoard } from '../models/models'
import { testCalculate } from '../services/puzzleCalculator'
import { drawPuzzleBoard } from '../services/puzzlePainter'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const calculate = () => {
    const board = testCalculate();
    //setBoardOutput(boardString);

    drawShape(board);
  }

  const drawShape = (board: PuzzleBoard) => {
            
    // Get the canvas element using the DOM
    var canvas = document.getElementById('mycanvas') as HTMLCanvasElement;

    // Make sure we don't execute when canvas isn't supported
    if (canvas.getContext) {
       
       // use getContext to use the canvas for drawing
       var ctx = canvas.getContext('2d') as CanvasRenderingContext2D;
       drawPuzzleBoard(board, ctx);
    } else {
       alert('You need Safari or Firefox 1.5+ to see this demo.');
    }
 }

  return (
    <div className={styles.container}>
      <Head>
        <title>Ni no Kuni: Cross Worlds Puzzle Solver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Puzzle Sover
        </h1>

        <div style={{margin: 15, display: 'flex', flexDirection: 'column'}}>
          <button onClick={calculate}>Calculate</button>
        </div>

        <canvas id="mycanvas" width="500" height="500" style={{border: '1px solid black'}}></canvas>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
